paths:
  source_folder: "Assets/"
  json_source_file: "data.json"
  json_destination_file: "data_mod2.json"
  yaml_destination_file: "data_ymod2.yaml"
serialization_source: 'object'
actions: ['somestats','serialize','convert_json_to_yaml']